twitter_clone/twitter/models.py
from twitter import db, login_manager
from datetime import datetime
from flask_login import UserMixin

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, nullable=False)
    email = db.Column(db.String, nullable=False, unique=True)
    password = db.Column(db.String(60), nullable=False)
    image_file = db.Column(db.String(20), nullable=False, default='default.jpg')
    posts = db.relationship('Post', backref='author')
    

    def __repr__(self):
        return f"User('{self.username}' '{self.email}', '{self.image_file}')"


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.Text(120), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.now)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return f"Post('{self.date_posted}' '{self.user_id}')"

twitter_clone/twitter/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

twitter_clone/twitter/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from twitter.models import User
from flask_login import current_user

class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=4, max=16)])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('Email alreay taken. Please choose a different one')

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=4, max=16)])
    submit = SubmitField('Login')

class UpdateProfileForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    username = StringField('Username', validators=[DataRequired()])
    picture = FileField('Profile Picture', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Update Profile')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user and current_user.email != user.email:
            raise ValidationError('Email alreay taken. Please choose a different one')

twitter_clone/twitter/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from twitter.config import Config

db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    from twitter.main.routes import main
    from twitter.users.routes import users
    from twitter.posts.routes import posts

    app.register_blueprint(main)
    app.register_blueprint(users)
    app.register_blueprint(posts)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)

    return app

twitter_clone/twitter/main/routes.py
from flask import Blueprint, render_template
from twitter.models import Post

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
def home():
    posts = Post.query.order_by(Post.date_posted.desc()).all()
    return render_template('home.html', title = "Home", posts = posts)

@main.route('/about')
def about():
    return render_template('about.html', title='About')

twitter_clone/twitter/posts/routes.py
from flask import Blueprint, render_template, redirect, request, abort, url_for
from flask_login import login_required, current_user
from twitter import db
from twitter.models import Post
from twitter.posts.forms import PostForm

posts = Blueprint('posts', __name__)

@posts.route('/post', methods=['GET', 'POST'])
@login_required
def post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(content=form.content.data, user_id=current_user.id)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('main.home'))
    return render_template('post.html', title='New Post', form=form)


@posts.route('/post/<int:post_id>')
def current_post(post_id):
    post = Post.query.get(int(post_id))
    return render_template('current_post.html', title='Post',post=post)

@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(int(post_id))
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.content = form.content.data
        db.session.commit()
        return redirect(url_for('main.home'))
    elif request.method == 'GET':
        form.content.data = post.content
    return render_template('post.html', title='Update Post', post=post, form=form)

@posts.route('/post/<int:post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(int(post_id))
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for('main.home'))

twitter_clone/twitter/users/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_user, logout_user, login_required, current_user
from twitter import db, bcrypt
from twitter.users.forms import RegistrationForm, LoginForm, UpdateProfileForm
from twitter.models import User, Post
from twitter.users.utils import crop_image

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data)
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('users.login'))
    return render_template('register.html', title="Register", form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        exists = bcrypt.check_password_hash(user.password, form.password.data)
        if user and exists:
            login_user(user)
            return redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful!')
    return render_template('login.html', title="Login", form=form)

@users.route('/profile/<username>', methods=['GET', 'POST'])
@login_required
def profile(username):
    posts = Post.query.filter_by(user_id=current_user.id).order_by(Post.date_posted.desc()).all()
    form = UpdateProfileForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_name = crop_image(form.picture.data)
            current_user.image_file = picture_name
        current_user.email = form.email.data
        current_user.username = form.username.data
        db.session.commit()
        return redirect(url_for('main.home'))
    elif request.method == 'GET':
        form.email.data = current_user.email
        form.username.data = current_user.username
    return render_template('profile.html', title=f'{current_user.username}', posts=posts, form=form)

@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.home'))

twitter_clone/twitter/templates/about.html
{% extends 'base.html' %}

{% block content %}
{% endblock %}

twitter_clone/twitter/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Twitter</title>
    {% endif %}
</head>
<body>
    <header>
        <ul class="nav">
          <li class="main-title">Twitter</li>
          <li class="three-lines-main">
            <div class="three-lines" onclick="myFunc()">
              <div></div>
              <div></div>
              <div></div>
            </div>
          </li>
          <div class="inner-links" id="inner-link">
            <li><a href="{{ url_for('main.home') }}">Home</a></li>
            <li><a href="{{ url_for('main.about') }}">About</a></li>
            {% if current_user.is_authenticated %}
            <li class="right"><a href="{{ url_for('users.logout') }}">Logout</a></li>
            <li class="right"><a href="{{ url_for('posts.post') }}">Post</a></li>
              <li class="right"><a href="{{ url_for('users.profile', username=current_user.username) }}">Profile</a></li>
            {% else %}
              <li class="right"><a href="{{ url_for('users.login') }}">Login</a></li>
              <li class="right"><a href="{{ url_for('users.register') }}">Register</a></li>
            {% endif %}
          </div>
        </ul>
      </header>
    <div class="main">
        {% block content %}{% endblock %}
    </div>

    <script>
        function myFunc() {
            let x = document.getElementById('inner-link');
            if(x.className === 'inner-links'){
                x.className += ' responsive';
            }else{
                x.className = 'inner-links';
            }
        }
    </script>

</body>
</html>

twitter_clone/twitter/templates/current_post.html
{% extends 'base.html' %}
{% block content %}

<div class="post-main-div login-form" >
    <div style="padding: 2%;">
        <span class="span-profile-pic">
            <img src="{{ url_for('static' ,filename='images/' + post.author.image_file) }}" alt="" class="profile-pic">
        </span>
        <div class="span-flex">
            <span class="user-name">
                {{ post.author.username }}
            </span>.
            <span class="date-posted">
                {{ post.date_posted.strftime('%b %d, %Y') }}
            </span>
            {% if (current_user == post.author) %}
                <div  class="update-btns">
                    <a class="btn" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                    <a class="btn dlt-btn" href="{{ url_for('posts.delete_post', post_id=post.id)}}">Delete</a>
                </div>
            {% endif %}
            <p class="post-content">
                {{ post.content }}
            </p>
        </div>
    </div>
</div>

{% endblock %}

twitter_clone/twitter/templates/home.html
{% extends 'base.html' %}
{% block content %}

<div class="post-main">
    {% for post in posts %}
        <a href="{{ url_for('posts.current_post', post_id=post.id) }}" style="text-decoration: none;">
            <div class="post-main-div">
                <span class="span-profile-pic">
                    <img src="{{ url_for('static' ,filename='images/' + post.author.image_file) }}" alt="{{ post.author.username }}" class="profile-pic">
                </span>
                <div class="span-flex">
                    <span class="user-name">
                        {{ post.author.username }}
                    </span>
                    <span class="date-posted">
                        {{ post.date_posted.strftime('%b %d, %Y') }}
                    </span>
                    <p class="post-content">
                        {{ post.content }}
                    </p>
                </div>
            </div>
        </a>
    {% endfor %}
</div>

{% endblock %}

twitter_clone/twitter/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Twitter</title>
    {% endif %}
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

twitter_clone/twitter/templates/login.html
{% extends 'layout.html' %}

{% block content %}
<div class="login-form">
    <div class="login-form-div">
        <h2>Login</h2>
        <div class="flash-msg">
            {% with messages = get_flashed_messages() %}
                {% for message in messages %}
                    <span>
                        {{ message }}
                    </span>
                {% endfor %}
            {% endwith %}
        </div>
        <form action="" method="POST">
            {{ form.hidden_tag() }}
        
            {{ form.email.label() }} <br>
            {{ form.email(class="form-input", placeholder='Email') }} <br>
            <div class="form-errors">
                {% if form.email.errors %}
                    {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        
            {{ form.password.label() }} <br>
            {{ form.password(class="form-input", placeholder='Password') }} <br>
            <div class="form-errors">
                {% if form.password.errors %}
                    {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        
            {{ form.submit(class="submit-btn") }}
        </form>
        <div class="account">
            Do not have an account? <br>
            <a href="{{ url_for('users.register') }}">Sign Up</a>
        </div> 
    </div>
</div>
{% endblock %}

twitter_clone/twitter/templates/post.html
{% extends 'base.html' %}

{% block content %}

<div class="login-form">
    <div class="login-form-div">
        <h2>New Post</h2>

        <form action="" method="POST">
            {{ form.hidden_tag() }}
        
            {{ form.content(class="form-input new-post") }} <br>
            <div class="form-errors">
                {% if form.content.errors %}
                    {% for error in form.content.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        
            {{ form.submit(class="submit-btn") }}
        </form>
    </div>
</div>
{% endblock %}

twitter_clone/twitter/templates/profile.html
{% extends 'base.html' %}

{% block content %}
{% if current_user.is_authenticated %}
    <div class="login-form">
        <div class="login-form-div">
            <span>
                <img class="profile-pic profile-pic-main" src="{{ url_for('static', filename='images/'+current_user.image_file) }}" alt="">
            </span>
            <div class="user-name-h1">
                <h1>{{ current_user.username }}</h1>
                <h3>{{ current_user.email }}</h3>
            </div>
            <h2>Update Profile</h2>
            <form action="" method="POST" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
            
                {{ form.email.label() }} <br>
                {{ form.email(class="form-input", placeholder='Email') }} <br>
                <div class="form-errors">
                    {% if form.email.errors %}
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            
                {{ form.username.label() }} <br>
                {{ form.username(class="form-input", placeholder='Username') }} <br>
                <div class="form-errors">
                    {% if form.username.errors %}
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    {% endif %}
                </div>

                {{ form.picture(class="form-input file-input") }} <br>
                <div class="form-errors">
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            
                {{ form.submit(class="submit-btn") }}
            </form>
        </div>
    </div>
{% endif %}

<div class="post-main">
    {% for post in posts %}
        <a href="{{ url_for('posts.current_post', post_id=post.id) }}" style="text-decoration: none;">
            <div class="post-main-div">
                <span class="span-profile-pic">
                    <img src="{{ url_for('static' ,filename='images/' + post.author.image_file) }}" alt="{{ post.author.username }}" class="profile-pic">
                </span>
                <div class="span-flex">
                    <span class="user-name">
                        {{ post.author.username }}
                    </span>
                    <span class="date-posted">
                        {{ post.date_posted.strftime('%b %d, %Y') }}
                    </span>
                    <p class="post-content">
                        {{ post.content }}
                    </p>
                </div>
            </div>
        </a>
    {% endfor %}
</div>

{% endblock %}

twitter_clone/twitter/templates/register.html
{% extends 'layout.html' %}
{% block content %}
<div class="login-form">
    <div class="login-form-div">
        <h2>Sign Up</h2>
        
        <form action="" method="POST">
            {{ form.hidden_tag() }}
        
            {{ form.username.label() }} <br>
            {{ form.username(class="form-input", placeholder='Username') }} <br>
            <div class="form-errors">
                {% if form.username.errors %}
                    {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                {% endif %}
            </div>

            {{ form.email.label() }} <br>
            {{ form.email(class="form-input", placeholder='Email') }} <br>
            <div class="form-errors">
                {% if form.email.errors %}
                    {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        
            {{ form.password.label() }} <br>
            {{ form.password(class="form-input", placeholder='Password') }} <br>
            <div class="form-errors">
                {% if form.password.errors %}
                    {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                {% endif %}
            </div>

            {{ form.confirm_password.label() }} <br>
            {{ form.confirm_password(class="form-input", placeholder="Confirm Password") }} <br>
            <div class="form-errors">
                {% if form.confirm_password.errors %}
                    {% for error in form.confirm_password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        
            {{ form.submit(class="submit-btn") }}
        </form>
        <div class="account">
            Already have an account? <br>
            <a href="{{ url_for('users.login') }}">Login</a>
        </div> 
    </div>
</div>
{% endblock %}